//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewBookingRoomDS
    {
        public string fio { get; set; }
        public string number { get; set; }
        public System.DateTime dtincheck { get; set; }
        public System.DateTime dtoutncheck { get; set; }
    }
}
